---
- hosts: centos
  gather_facts: no
  become: yes

  pre_tasks:
    - name: create resolv-file for dnsmasq
      ansible.builtin.copy:
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        dest: /etc/resolv.dnsmasq

  roles:
   - dnsmasq


