---
# handlers file for nginx_php_fpm
- name: restart fpm
  ansible.builtin.service:
    name: "php8.1-fpm"
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart nginx
  ansible.builtin.service:
    name=nginx 
    state=restarted
